<?php

namespace MOETableGenerator;

class MOEIndices {

  /**
   * Returns the index of each field as named in the specification
   * Useful for indexing into a row of the .moe by the name of the field
   * instead of a magic number
   * @return Array
   */
  public static function getIndices() {
    return array(
      'SCHOOL_ID' => 0,
      'STUDENT_ID' => 1,
      'NSN' => 2,
      'SURNAME' => 3,
      'FIRSTNAME' => 4,
      'GENDER' => 5,
      'DOB' => 6,
      'FIRST ATTENDANCE' => 7,
      'FIRST SCHOOLING' => 8,
      'ETHNIC1' => 9,
      'ETHNIC2' => 10,
      'ETHNIC3' => 11,
      'IWI' => 12,
      'IWI2' => 13,
      'IWI3' => 14,
      'ORS and Section 9' => 15,
      'FUNDING YEAR LEVEL' => 16,
      'TYPE' => 17,
      'PREVIOUS SCHOOL' => 18,
      'ZONING STATUS' => 19,
      'COUNTRY OF CITIZENSHIP' => 20,
      'FEE' => 21,
      'FTE' => 22,
      'MAORI' => 23,
      'LAST ATTENDANCE' => 24,
      'NQF QUAL' => 25,
      'REASON' => 26,
      'ECE' => 27,
      'PACIFIC MEDIUM - LANGUAGE' => 28,
      'PACIFIC MEDIUM - LEVEL' => 29,
      'SUBJECT 1' => 30,
      'MODE OF INSTRUCTION SUBJECT 1' => 31,
      'HOURS PER YEAR SUBJECT 1' => 32,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 1' => 33,
      'SUBJECT 2' => 34,
      'MODE OF INSTRUCTION SUBJECT 2' => 35,
      'HOURS PER YEAR SUBJECT 2' => 36,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 2' => 37,
      'SUBJECT 3' => 38,
      'MODE OF INSTRUCTION SUBJECT 3' => 39,
      'HOURS PER YEAR SUBJECT 3' => 40,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 3' => 41,
      'SUBJECT 4' => 42,
      'MODE OF INSTRUCTION SUBJECT 4' => 43,
      'HOURS PER YEAR SUBJECT 4' => 44,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 4' => 45,
      'SUBJECT 5' => 46,
      'MODE OF INSTRUCTION SUBJECT 5' => 47,
      'HOURS PER YEAR SUBJECT 5' => 48,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 5' => 49,
      'SUBJECT 6' => 50,
      'MODE OF INSTRUCTION SUBJECT 6' => 51,
      'HOURS PER YEAR SUBJECT 6' => 52,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 6' => 53,
      'SUBJECT 7' => 54,
      'MODE OF INSTRUCTION SUBJECT 7' => 55,
      'HOURS PER YEAR SUBJECT 7' => 56,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 7' => 57,
      'SUBJECT 8' => 58,
      'MODE OF INSTRUCTION SUBJECT 8' => 59,
      'HOURS PER YEAR SUBJECT 8' => 60,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 8' => 61,
      'SUBJECT 9' => 62,
      'MODE OF INSTRUCTION SUBJECT 9' => 63,
      'HOURS PER YEAR SUBJECT 9' => 64,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 9' => 65,
      'SUBJECT 10' => 66,
      'MODE OF INSTRUCTION SUBJECT 10' => 67,
      'HOURS PER YEAR SUBJECT 10' => 68,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 10' => 69,
      'SUBJECT 11' => 70,
      'MODE OF INSTRUCTION SUBJECT 11' => 71,
      'HOURS PER YEAR SUBJECT 11' => 72,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 11' => 73,
      'SUBJECT 12' => 74,
      'MODE OF INSTRUCTION SUBJECT 12' => 75,
      'HOURS PER YEAR SUBJECT 12' => 76,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 12' => 77,
      'SUBJECT 13' => 78,
      'MODE OF INSTRUCTION SUBJECT 13' => 79,
      'HOURS PER YEAR SUBJECT 13' => 80,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 13' => 81,
      'SUBJECT 14' => 82,
      'MODE OF INSTRUCTION SUBJECT 14' => 83,
      'HOURS PER YEAR SUBJECT 14' => 84,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 14' => 85,
      'SUBJECT 15' => 86,
      'MODE OF INSTRUCTION SUBJECT 15' => 87,
      'HOURS PER YEAR SUBJECT 15' => 88,
      'INSTRUCTIONAL YEAR LEVEL SUBJECT 15' => 89,
      'TUITION WEEKS' => 90,
      'NON-NQF QUAL' => 91,
      'UE' => 92,
      'EXCHANGE SCHEME' => 93,
      'BOARDING STATUS' => 94,
      'ADDRESS1' => 95,
      'ADDRESS2' => 96,
      'ADDRESS3' => 97,
      'ADDRESS4' => 98,
      'ELIGIBILITY CRITERIA' => 99,
      'VERIFICATION DOCUMENT' => 100,
      'SERIAL NUMBER' => 101,
      'CURRENT YEAR LEVEL' => 102,
      'POST-SCHOOL ACTIVITY' => 103,
      'PRIVACY INDICATOR' => 104,
      'MIDDLE NAME(S)' => 105,
      'PREFERRED FIRST NAME' => 106,
      'PREFERRED LAST NAME' => 107,
      'EXPIRY DATE' => 108,
      'STP' => 109,
      'WITHHOLD CONTACT DETAILS' => 110,
      'HOME PHONE DETAILS' => 111,
      'CELL PHONE NUMBER' => 112,
      'ALTERNATIVE PHONE NUMBER' => 113,
      'EMAIL ADDRESS' => 114,
      'CONTACT 1 SURNAME' => 115,
      'CONTACT 1 FIRSTNAME' => 116,
      'CONTACT 1 ADDRESS1' => 117,
      'CONTACT 1 ADDRESS2' => 118,
      'CONTACT 1 ADDRESS3' => 119,
      'CONTACT 1 ADDRESS4' => 120,
      'CONTACT 1 ADDRESS5' => 121,
      'CONTACT 1 PHONE NUMBER' => 122,
      'CONTACT 2 SURNAME' => 123,
      'CONTACT 2 FIRSTNAME' => 124,
      'CONTACT 2 ADDRESS1' => 125,
      'CONTACT 2 ADDRESS2' => 126,
      'CONTACT 2 ADDRESS3' => 127,
      'CONTACT 2 ADDRESS4' => 128,
      'CONTACT 2 ADDRESS5' => 129,
      'CONTACT 1=2 PHONE NUMBER' => 130,
      'STAR' => 131
    );

  }
}
